sudo: required
services:
  - docker

before_install:
  - docker build -t valentergs/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true valentergs/react-test npm test -- --coverage

after_success:
  - docker build -t valentergs/multi-client ./client
  - docker build -t valentergs/multi-nginx ./nginx
  - docker build -t valentergs/multi-server ./server
  - docker build -t valentergs/multi-worker ./worker
  # Login in to the Docker CLI - é preciso incluir ID e SENHA do Docker dentro do setup/enviroment to Travis CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push valentergs/multi-client
  - docker push valentergs/multi-nginx
  - docker push valentergs/multi-server
  - docker push valentergs/multi-worker

deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-sa-east-1-340831665464
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
